import type { NextPage } from 'next';
import Head from 'next/head';
import FeatureItem from 'src/components/FeatureItem';
import HeroSection from 'src/components/HeroSection';
import Highlights from 'src/components/Highlights';
import NavBar from 'src/components/NavBar';
import Showcase from 'src/components/Showcase';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<NavBar></NavBar>
			<HeroSection></HeroSection>
			<Highlights></Highlights>
			<FeatureItem />
			<div className='w-2/3 mx-auto mb-10'>
				<Showcase />
			</div>
		</>
	);
};

export default Home;
