import type { NextPage } from "next";
import Head from "next/head";
import FeatureItem from "src/components/FeatureItem";
import HeroSection from "src/components/HeroSection";
import Highlights from "src/components/Highlights";
import NavBar from "src/components/NavBar";
import Showcase from "src/components/Showcase";
import ReviewCard from "src/components/review/ReviewCard";

const Container = ({ children }: { children: React.ReactNode }) => {
  return <div className="w-2/3 mx-auto mb-10">{children}</div>;
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar></NavBar>
      <HeroSection></HeroSection>
      <Highlights></Highlights>
      <FeatureItem />
      <Container>
        <Showcase />
      </Container>

      <Container>
        <div className="flex  items-center justify-center bg-gradient-to-r from-cyan-500 to-blue-500 gap-5 p-8 rounded-lg ">
          <div className="text-white">
            <h4 className="text-2xl">Register For Free & Start Bidding Now!</h4>
            <small>From cars to diamonds to iPhones, we have it all.</small>
          </div>
          <div>
            <button className="btn px-5 py-2  text-purple-600 bg-white hover:bg-purple-700  hover:text-white rounded-full focus:outline-none focus:ring focus:ring-violet-300">
              REGISTER
            </button>
          </div>
        </div>
      </Container>
      <Container>
        <div className="bg-white p-6  rounded-lg ">
          <h4 className="text-xl text-blue-600 font-semibold">
            Subscribe to Sbidu
          </h4>
          <h1 className="text-2xl m-2 font-bold">To Get Exclusive Benefits</h1>
          <div className="flex mt-4">
            <input
              type="email"
              name="email"
              placeholder="Enter Your Email "
              required
              className="p-2 border-2 rounded-full "
            />
            <button className="-ml-9 text-lg text-white  px-6 py-2 rounded-full  bg-gradient-to-r from-blue-700 via-blue-800 to-blue-900 hover:text-white focus:outline-none focus:ring focus:ring-violet-300">
              SUBSCRIBE
            </button>
          </div>
        </div>
      </Container>
      <ReviewCard />
    </>
  );
};

export default Home;
